package de.fraunhofer.iosb.iad.maritime.datamodel;

public enum VesselType {
	FISHING, TOWING, DIVING, MILITARY, SAILING, PLEASURE, PILOT, SEARCH_AND_RESCUE, TUG, PORT_TENDER, ANTI_POLLUTION,
	LAW, MEDICAL, RR_18, WIG, HIGH_SPEED, PASSENGER, CARGO, TANKER, NON_SPECIFIED, FISHING_VESSEL, PASSENGER_SHIP,
	VESSEL, SPECIAL_PURPOSE_SHIP, GENERAL_CARGO_SHIP, OTHER, BULK_CARRIER, HIGH_SPEED_CRAFT, SPARE,
	MOBILE_OFF_SHORE_DRILLING_UNIT, OIL_TANKER, UNDERWATERNUCLEAR_SHIP, NUCLEAR_SHIP
}
